FROM digantv/openjdk:latest

RUN apt-get update
RUN apt-get install -y openjdk-17-jdk
RUN apt-get install -y git
RUN apt-get install -y maven

WORKDIR /app

COPY /target/directory-service-0.0.1-SNAPSHOT.jar /app/directory-service.jar

EXPOSE 8081

CMD ["java", "-jar", "directory-service.jar"]

