FROM digantv/openjdk:latest

RUN apt-get update
RUN apt-get install -y openjdk-17-jdk
RUN apt-get install -y git
RUN apt-get install -y maven

WORKDIR /app

COPY /target/patient-service-0.0.1-SNAPSHOT.jar /app/patient-service-0.0.1-SNAPSHOT.jar

EXPOSE 8082

CMD ["java", "-jar", "patient-service-0.0.1-SNAPSHOT.jar"]