FROM digantv/openjdk:latest

RUN apt-get update
RUN apt-get install -y openjdk-17-jdk
RUN apt-get install -y git
RUN apt-get install -y maven

WORKDIR /app

COPY /target/appointment-service-0.0.1-SNAPSHOT.jar /app/appointment-service-0.0.1-SNAPSHOT.jar 

EXPOSE 8084

CMD ["java", "-jar", "appointment-service-0.0.1-SNAPSHOT.jar"]