FROM digantv/openjdk:latest

RUN apt-get update
RUN apt-get install -y openjdk-17-jdk
RUN apt-get install -y git
RUN apt-get install -y maven

WORKDIR /app

COPY /target/case-service-latest.jar /app/case-service-latest.jar

EXPOSE 8083

CMD ["java", "-jar", "case-service-latest.jar"]

