name: Api Gateway CI/CD Workflow

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Perform google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:format
        working-directory: hospital-management/api-gateway

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=.

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Push Docker Image
        run: |
          docker push digantv/api-gateway:latest
        working-directory: hospital-management/api-gateway

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Push docker images
        run: |
          cd hospital-management/api-gateway
          CURRENT_FOLDER_NAME=$(basename $(pwd))
          docker push ${{secrets.CONTAINER_REGISTRY_URL}}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
