name: case-service-ci

on:
  push:
    branches:
      - main

jobs:
  build-case-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=.

      - name: Build Case Service
        run: docker build -t ${{secrets.DOCKER_REGISTRY_USER}}/case-service:latest -f case-service.dockerfile .

      - name: Login to Github Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Push Docker Images
        run: docker push ${{secrets.DOCKER_REGISTRY_USER}}/case-service:latest
