name: hospital-console-fxml-build

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate and run Commands
        working-directory: the-mono-repo/hospital-console-fxml
        run: |
          echo "Current Directory: $(pwd)"
          ls

      - name: Build code
        working-directory: the-mono-repo/hospital-console-fxml
        run: mvn clean install
